import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import { Outfit } from "next/font/google";
import "./globals.css";

const lexend = Lexend({
  subsets: ["latin"],
  weight: "300",
  variable: "--font-lexend",
});

const outfit = Outfit({
  subsets: ["latin"],
  weight: "300",
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexend.variable} ${outfit.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
